#90 [US04] Sair da Conta
fga-eps-mds/2020.2-Hortum-Mobile pull request #13
Opened 2021-03-26 21:40 UTC by CarlosFiuza

## Descrição
- Exclusão dos tokens e atributos do usuário logado ao clicar em sair da conta

## Está concertando alguma issue aberta?
- [#90](https://github.com/fga-eps-mds/2020.2-Hortum/issues/90)

## Tarefas gerais realizadas
- Tokens e informações do usuário logado apagadas
- Navigator para a tela de login

2021-03-26 23:01 UTC, Joao-Moura requested changes
Valeu pelo PR, só deixando um comentário. De resto é isso, parabéns.

2021-03-26 23:01 UTC, Joao-Moura commented on hortum_mobile/lib/model/user.dart
> +    deleteSecureData('token_access');
Faltou deletar o email também já que ele é salvo junto no secure_storage

2021-03-26 23:12 UTC, CarlosFiuza commented on hortum_mobile/lib/model/user.dart
> +    deleteSecureData('token_access');
Corrigido.

2021-03-27 01:03 UTC, brenno-silva approved these changes
Tudo certo.

2021-03-27 12:56 UTC, Joao-Moura approved these changes
Show.

2021-03-27 12:56 UTC, merged