HOTFIX - Padronização dos arquivos
fga-eps-mds/2020.2-Hortum-Mobile pull request #17
Opened 2021-03-30 20:28 UTC by VitorLamego

## Descrição
Para este pull request foi realizado a padronização das pastas do projeto, assim como alteração de alguns arquivos, principalmente na criação de componentes para os mesmos.

## Está concertando alguma issue aberta?
#129

## Tarefas gerais realizadas
Adicione aqui as tarefas realizadas
- Criação de pastas 'services' para os componentes que possuem métodos de validação ou outros serviços relacionados ao servidor
- Criação de componentes nos arquivos principais
- Remoção da pasta 'page' dentro do diretório 'announcemets_register'
- Criação de uma variável global para IPLOCAL

2021-03-31 08:21 UTC, CarlosFiuza requested changes
o form_field.dart que está dentro de lib/views/register/components/ não está sendo usado, acho que poderia excluir esse arquivo.

2021-03-31 08:21 UTC, CarlosFiuza commented on hortum_mobile/lib/views/home_customer/home_customer_page.dart
> +import 'package:hortum_mobile/components/announcements_data.dart';
não está sendo usado esses imports.

2021-03-31 08:21 UTC, CarlosFiuza commented on hortum_mobile/lib/views/home_customer/home_customer_page.dart
> +import 'package:hortum_mobile/views/home_productor/components/list_announcements.dart';
esse também da linha 7

2021-03-31 12:00 UTC, brenno-silva approved these changes
Com exceção do que o Carlos falou, está tudo certo.

2021-03-31 13:55 UTC, VitorLamego commented
O componente form_field está sendo utilizado dentro do arquivo register_form, na mesma pasta

2021-03-31 23:17 UTC, CarlosFiuza requested changes
o CustomFormField() que está sendo usado no register_form é o que vem dos components global, e não o que está em register/components

2021-03-31 23:37 UTC, VitorLamego commented
Sim, tem razão !! Exclui o arquivo.

2021-04-01 00:08 UTC, CarlosFiuza approved these changes
Trabalho muito bom pessoal, vlww.

2021-04-01 02:05 UTC, merged