Feature/162 codequality ci cd
fga-eps-mds/2020.2-Hortum-Mobile pull request #29
Opened 2021-04-09 19:22 UTC by matheuscvp

## Descrição
- Implementação de ferramenta de avaliação de qualidade de software

## Está concertando alguma issue aberta?
- [#162](https://github.com/fga-eps-mds/2020.2-Hortum/issues/162#issue-853798135) 

## Tarefas gerais realizadas
- Adição do analysis_options.yaml, arquivo referente a regras usadas para avaliação de código
- Adição da dependência flint ao pubspec.yaml, dependência que será usada no flutter analyze 
- Correções de erros apontados pelo flutter analyze

### Como a analise de código irá funcionar
- Assim que aberto um pull request, o GitHub actions rodará o Flutter_CI.yml, onde fará os testes unitários, com o comando flutter test.
- Após os testes unitários, ele executará o comando flutter analyze que fará a analise no código e apontará, se houver, erros na construção do código, como: falha de endentação, variáveis inutilizadas, imports inutilizados, etc ...
- Para ter uma visão acerca do que foi apontado, ou não, basta olhar os logs do PR no actions

### Testando a analise: 
- Abra o repositório local, 2020.2-Hortum-Mobile, e de o comando flutter analyze no terminal. 

- Não retornará nenhum erro. Assim tendo que fazer algum erro proposital, ou uma mudança nas rules no arquivo: analysis_options.yaml, e rodar o flutter analyze de novo para ver os erros retornados.

2021-04-09 19:35 UTC, VitorLamego requested changes

2021-04-09 19:35 UTC, VitorLamego commented on hortum_mobile/lib/views/home_productor/components/list_announcements.dart
> +    //Size size = MediaQuery.of(context).size;
Esse aqui não precisa comentar não, pode apagar. Não está sendo utilizado neste arquivo e acredito que também não será no futuro, então não tem importância apagar não.

2021-04-09 19:35 UTC, VitorLamego commented on hortum_mobile/lib/views/login/login_page.dart
> +//import 'package:http/http.dart' as http;
Pode apagar esse import também, provavelmente devem ter utilizado e depois apgado e o import permanece, mas considerando que ele não está sendo usado agora e que nós iremos utilizar o Dio posteriomente, então não tem problema apagar também.

2021-04-09 19:35 UTC, VitorLamego commented on hortum_mobile/lib/components/photo_select.dart
> +//import 'dart:io';
Esse import também não vai ser utilizado. Pode apagar.

2021-04-09 19:35 UTC, VitorLamego commented on hortum_mobile/analysis_options.yaml
> +# include: package:lint/analysis_options.yaml
Precisa desses comentários mesmo ou so o flint que vai ser utilizado ? Se posteriormente for útil para vocês ai não tem problema, mas se não forem usar acredito que pode apagar mesmo

2021-04-09 22:03 UTC, VitorLamego approved these changes
Boa !! Acredito que seja isso mesmo !! Parabéns.

2021-04-11 01:16 UTC, vital14 approved these changes
Não encontrei mais nenhum problema além do que ja foi citado, parabens

2021-04-11 01:24 UTC, merged