157 Homepage Produtor
fga-eps-mds/2020.2-Hortum-Mobile pull request #33
Opened 2021-04-15 13:29 UTC by matheuscvp

## Descrição
- Atualização da homepage do produtor

## Está concertando alguma issue abertas?
- [#157](https://github.com/fga-eps-mds/2020.2-Hortum/issues/157#issue-853774667)

## Tarefas gerais realizadas
- Adição de Classe para fazer requisição dos anúncios do produtor logado
- Refatoração na homepage para tratar e apresentar corretamente os anuncios
- Correção do botão de deletar anuncio

### Testando
- Entre como um produtor e cadastre um anuncio ou mais 
- Atualizando a página aparecerá seus anúncios

2021-04-15 13:38 UTC, VitorLamego requested changes
A branch está quebrando alguns testes, verificar o que aconteceu e fazer as alterações necessárias.

2021-04-15 13:41 UTC, matheuscvp commented
> A branch está quebrando alguns testes, verificar o que aconteceu e fazer as alterações necessárias.

2021-04-15 13:42 UTC, matheuscvp commented
Então parece que ta quebrando por causa do IPLOCAL e não em um teste em si

2021-04-15 13:47 UTC, VitorLamego commented
Na verdade não, acontece que a branch não está atualizada com o código da main, rode o comando:

```
git pull origin main
```

2021-04-20 14:52 UTC, VitorLamego requested changes
Deixei alguns comentários que precisam de alteração. E também vejam a questão dos testes, além dos métodos que citei nos comentários dá pra fazer teste para ver se ele está renderizando os anúncios corretos, conforme o response recebido.

2021-04-20 14:52 UTC, VitorLamego commented on hortum_mobile/lib/data/prod_log_data_backend.dart
> +    //Uri.http('http://$ip:8000/productor/retrieve/${encodedEmail}', "");
Como são comentários relacionados à utilização do pacote http, pode apagar isso ai.

2021-04-20 14:52 UTC, VitorLamego commented on hortum_mobile/lib/data/prod_log_data_backend.dart
> +    //var response = await http.get(urli, headers: header);
Esse comentário também.

2021-04-20 14:52 UTC, VitorLamego commented on hortum_mobile/lib/data/prod_log_data_backend.dart
> +  var productor;
Essa variável é desnecessária, você pode passar os anúncios direto por respose.data['announcements']

2021-04-20 14:52 UTC, VitorLamego commented on hortum_mobile/lib/services/codec_string.dart
> +}
Necessário a realização de testes desses dois métodos.

2021-04-20 14:52 UTC, VitorLamego commented on hortum_mobile/lib/views/home_productor/components/list_announcements.dart
> +//import 'package:hortum_mobile/components/announcements_data.dart';
Remover comentário. Os imports que não forem mais utilizados podem ser apagados e não comentados.

2021-04-20 14:52 UTC, VitorLamego commented on hortum_mobile/lib/views/home_productor/home_productor_page.dart
> +        builder: (BuildContext context, AsyncSnapshot snapshot) {
O FutureBuilder é utilizado para renderizar interfaces que dependem de eventos assíncronos, sendo assim existe a possibilidade do evento demorar muito para ser finalizado, o que geraria nesse caso em uma tela branca para o usuário.

Para a resolução desse problema, utilize o snapshot.connectionState. Mais precisamente, você precisa retornar algo quando o snapshot.connectionState != ConnectionState.done.

Na tela principal de consumidor foi retornado um Spin Kit para que o usuário saiba que a informação está carregando. Dê uma olhada no arquivo home_customer_page.dart

2021-04-20 14:52 UTC, VitorLamego commented on hortum_mobile/lib/views/home_productor/home_productor_page.dart
> +        builder: (BuildContext context, AsyncSnapshot snapshot) {
O FutureBuilder é utilizado para renderizar interfaces que dependem de eventos assíncronos, sendo assim existe a possibilidade do evento demorar muito para ser finalizado, o que geraria nesse caso em uma tela branca para o usuário.

Para a resolução desse problema, utilize o snapshot.connectionState. Mais precisamente, você precisa retornar algo quando o snapshot.connectionState != ConnectionState.done.

Na tela principal de consumidor foi retornado um Spin Kit para que o usuário saiba que a informação está carregando. Dê uma olhada no arquivo home_customer_page.dart

2021-04-20 14:52 UTC, VitorLamego commented on hortum_mobile/test/home_productor_page_test.dart
> +  };
Alterar dados desta variável. Utilize exemplos reais ao que pode ser cadastrado por um usuário e coloque valores de teste.

2021-04-20 14:52 UTC, VitorLamego commented on hortum_mobile/lib/data/auto_login_backend.dart
> +    actualUser.deleteUser();
Essa alteração não pode ir para a main teoricamente, se não o login automático nunca funcionaria. Deixe ela local mesmo.

2021-04-20 17:16 UTC, matheuscvp commented on hortum_mobile/lib/data/prod_log_data_backend.dart
> +  var productor;
mas mesmo assim tenho que guardar em alguma variavel n?

2021-04-20 18:57 UTC, VitorLamego commented on hortum_mobile/lib/data/prod_log_data_backend.dart
> +  var productor;
Eu não vi essa variável sendo utilizada em nenhum lugar no código, a não ser quando passou o productor['announcements']. Ai nessa ocasião é possível passar direto do response.data['announcements'], mas se estiver utilizando a variável ou futuramente irá utilizá-la ai tudo bem.

2021-04-20 21:44 UTC, VitorLamego approved these changes
Só a variável productor que até agora não entendi a utilidade, mas como não comentaram nada e ela permaneceu no código acredito que ela possa vir a ter alguma funcionalidade futuramente. Parabéns pelo trabalho !!

2021-04-20 23:09 UTC, matheuscvp commented on hortum_mobile/lib/data/prod_log_data_backend.dart
> +  var productor;
a entendi errado

2021-04-20 23:36 UTC, brenno-silva requested changes
Muito bom, mas duas correções:
- No list_announcements.dart troque o` title: announcements[index]['title'] `para `title: announcements[index]['name'] `
-  `category: announcements[index]['category']),` para `category: announcements[index]['type_of_product']),`

Agora é mais por estética mesmo(Se quiser ignorar fique a vontade): 
- Mudar o estilo da mensagem que aparece quando não possui anúncio para ficar semelhante ao que está na HomePage do customer `Text(
                  "Infelizmente!!\nNão encontramos nenhum resultado para a sua busca",
                  textAlign: TextAlign.center,
                  style: TextStyle(color: Color(0xff1D8E40), fontSize: 15),`

2021-04-21 21:01 UTC, matheuscvp commented
Porem se eu fizer isso vai dar conflito, deixei assim porque estava dando conflito

2021-04-22 01:17 UTC, brenno-silva approved these changes
Acredito que esteja tudo correto. Bom trabalho!

2021-04-22 14:04 UTC, merged