#92 [US06] Atualizar Dados de Usuário
fga-eps-mds/2020.2-Hortum-Mobile pull request #34
Opened 2021-04-16 01:43 UTC by CarlosFiuza

## Descrição
- Criação de page ChangePassword para mudar senha
- Refatoração de page Profile para mudar dados do usuário

## Está concertando alguma issue aberta?
- [#92](https://github.com/fga-eps-mds/2020.2-Hortum/issues/92)

## Tarefas gerais realizadas
- Criação page ChangePassword
- Criação service ChangePassword
- Criação data ChangePassword
- Refatoração page Profile
- Criação service Profile
- Criação data Profile
- Adição das novas telas no protótipo de alto nível

2021-04-18 16:23 UTC, LucasBraunX approved these changes
Funcionando certinho e de acordo com o protótipo. E pelos testes que fiz não encontrei nenhum caso em que não funciona.

2021-04-18 18:30 UTC, VitorLamego requested changes
Fizeram um trabalho muito bom pessoal !! Vi que alteraram algumas formas de criação de estado nas classes e algumas outras mudanças. Deixei alguns pequenos comentários somente para seguirmos com o padrão do projeto e para que seja feito alguns ajustes. Parabéns !! O trabalho como um todo ficou muito bom.

2021-04-18 18:30 UTC, VitorLamego commented on hortum_mobile/lib/views/change_password/services/change_password_services.dart
> +class ChangeServices {
Acredito ser melhor nomear esta classe como ChangePasswordServices, para seguir o padrão das outras e ficar mais claro que tipo de serviço é esse.

2021-04-18 18:30 UTC, VitorLamego commented on hortum_mobile/lib/views/profile/services/profile_services.dart
> +    final user = actualUser;
Acredito que essas variáveis são desnecessárias. Como o valor já está vindo por parâmetro, não entendi o porquê de gastar memória para armazenar esses valores novamente.

2021-04-18 18:30 UTC, VitorLamego commented on hortum_mobile/lib/views/change_password/services/change_password_services.dart
> +    final user = actualUser;
Acredito que essas variáveis são desnecessárias. Como o valor já está vindo por parâmetro, não entendi o porquê de gastar memória para armazenar esses valores novamente.

2021-04-18 18:30 UTC, VitorLamego commented on hortum_mobile/test/change_password_page_test.dart
> +      // expect(find.byType(CustomFormField), findsNWidgets(3));
Remover comentário

2021-04-18 20:31 UTC, CarlosFiuza commented on hortum_mobile/lib/views/change_password/services/change_password_services.dart
> +class ChangeServices {
Ok

2021-04-18 20:43 UTC, CarlosFiuza commented on hortum_mobile/lib/views/profile/services/profile_services.dart
> +    final user = actualUser;
Ok

2021-04-18 20:44 UTC, CarlosFiuza commented on hortum_mobile/lib/views/change_password/services/change_password_services.dart
> +    final user = actualUser;
Ok

2021-04-18 20:44 UTC, CarlosFiuza commented on hortum_mobile/test/change_password_page_test.dart
> +      // expect(find.byType(CustomFormField), findsNWidgets(3));
Ok

2021-04-19 14:27 UTC, VitorLamego approved these changes

2021-04-19 14:27 UTC, VitorLamego approved these changes

2021-04-19 18:12 UTC, merged