#94[US08] Editar Anúncio
fga-eps-mds/2020.2-Hortum-Mobile pull request #35
Opened 2021-04-19 20:20 UTC by brenno-silva

## Descrição
- Implementada a funcionalidade de editar um anúncio na frontend.

## Está concertando alguma issue aberta?
- [#94](https://github.com/fga-eps-mds/2020.2-Hortum/issues/94)

## Tarefas gerais realizadas
- Criação da tela edit_page
- Adição da _data_ de comunicação com o backend
- Dialog para avisar possível erro
- Adição do CustomDescField para a descrição de anúncios
-  Criação de testes para a tela e para a respectiva _data_

2021-04-19 21:21 UTC, CarlosFiuza requested changes
Muito bom, funcionando de acordo com o proposto. Parabéns
Só precisa fazer uma pequena alteração no services de editar anúncio

2021-04-19 21:21 UTC, CarlosFiuza commented on hortum_mobile/lib/views/edit_announ/services/edit_announ_services.dart
> +              response.data.toString(),
Só precisa rever a mensagem de erro que aparece no dialog alert, está codificada

2021-04-20 02:11 UTC, brenno-silva commented on hortum_mobile/lib/views/edit_announ/services/edit_announ_services.dart
> +              response.data.toString(),
Bem lembrado.

2021-04-20 15:27 UTC, LucasBraunX approved these changes
Funcionando muito bem, parabéns!

2021-04-20 17:19 UTC, CarlosFiuza approved these changes
Muito bom, valeu pessoal!

2021-04-20 18:30 UTC, merged