Feature/161 detalhe anuncio
fga-eps-mds/2020.2-Hortum-Mobile pull request #37
Opened 2021-04-22 17:32 UTC by vital14

## Descrição
- Criação de página com detalhes de anúncio

## Está concertando alguma issue aberta?
- #161

## Tarefas gerais realizadas
Adicione aqui as tarefas realizadas
- Transformando announcement box em botões
- Criação da tela de detalhes

2021-04-22 18:55 UTC, Joao-Moura requested changes
Primeiramente parabéns por conseguir fazer o carrousel funcionar kkkkkk. Agora umas coisas que eu acho que seriam interessantes mudar:
1. Senti a página muito apertada (principalmente o título muito pequeno e os widgets muito grudados)
2. Se possível adicionar um scroll na página
3. A descrição esta fixa ? Porque criando aqui anúncios com difrentes descrições continuou o mesmo texto
4. O ícone do campo descrição ta o mesmo que o da localização

2021-04-22 22:46 UTC, CarlosFiuza requested changes
Acho que poderia diminuir a caixa de texto da localização, visto que vai ser apenas uma String. Assim conseguiria liberar mais espaço na tela, que ficou bem apertada

2021-04-22 22:46 UTC, CarlosFiuza commented on hortum_mobile/lib/views/announcement_details/announcement_details_page.dart
> +                            "Brócolis recentemente plantado em um local perto de lorem ipsum Brócolis recentemente plantado em um local perto de lorem ipsum Brócolis recentemente plantado em um local
Aqui você usa uma descrição estática ao invés da descrição do anúncio obtido no data

2021-04-26 17:36 UTC, matheuscvp commented
Me intrometendo aqui, falta também os testes dessa página, pode ser testes básicos, sendo necessário apenas que ele execute o maior número de linhas de código possíveis dos arquivos criados. Motivo : com a adição destes arquivos perderemos 8% de cobertura de testes.

2021-05-02 03:25 UTC, Joao-Moura reviewed
Funcionando perfeitamente. Só uma coisa que eu acho que seria massa colocar mais não é obrigatório (por isso o comentário) é linkar o perfil do produtor na foto dele quando vc clica nos detalhes. De resto é isso, parabens.

E pro carlinhos que também vai ter que revisar (e se for usar a main no backend) tem que adicionar a seguinte linha no arquivo `announcements_backend`:
```dart
Map params = {
    "email": email,
    ...
    "images": [],
    "localizations": []
}
```

2021-05-02 19:54 UTC, CarlosFiuza requested changes
Parabéns pelo trabalho, ficou muito bom!
Só fiz uma observação quanto ao botão de compartilhar, que não será mais necessário.

2021-05-02 19:54 UTC, CarlosFiuza commented on hortum_mobile/lib/views/announcement_details/components/title_buttons_row.dart
> +      ),
Como não temos mais a user story de compartilhar anúncio não é mais necessário esse botão

2021-05-04 01:53 UTC, Joao-Moura commented
Agora sim, funcionando perfeitamente. Eu pelo menos não encontrei mais nenhum erro. Parabéns.

2021-05-04 01:54 UTC, Joao-Moura approved these changes
Agora sim, funcionando perfeitamente. Eu pelo menos não encontrei mais nenhum erro. Parabéns.

2021-05-04 12:10 UTC, CarlosFiuza approved these changes

2021-05-04 12:46 UTC, merged