#180 #107 Denunciar usuário
fga-eps-mds/2020.2-Hortum-Mobile pull request #41
Opened 2021-04-25 07:37 UTC by CarlosFiuza

## Descrição
- Criação de nova view Reclamation com respectivos components, services e page.

## Está concertando alguma issue aberta?
- #180
- #107

## Tarefas gerais realizadas
- Criação de tela de reclamações para listar todas as reclamações de um productor
- Criação de tela para registrar reclamação
- Criação de testes

2021-04-25 13:40 UTC, brenno-silva approved these changes
Tudo funcionando, bom trabalho.

2021-04-26 17:21 UTC, VitorLamego requested changes
Apontei algumas mudanças que acredito serem necessárias, qualquer dúvida ou discordância só comentar. E um pedido é que seja alterado as palavras "Reclamation", que em inglês não possui o mesmo significado do desejado em nossa aplicação.

Para essa mudança, sugiro utilizar o atalho existente no VsCode (Ctrl+Shift+F) o qual você consegue substituir todas as palavras em todos os arquivos por alguma outra que tenha vontade, então acredito que com isso fique bem simples de realizar essa alteração. Para ajudar ainda mais, utilize a ferramente de substituir as palavras com o CamelCase igual, assim todos os casos "reclamations" seriam substituídos, por exemplo, por "reclamacao" e todos os casos "Reclamations", substituídos por "Reclamacao". Acredito que isso ajudaria para não quebrar nenhum nome de classe ou algo do tipo.

O termo que utilizei "Reclamacao" foi apenas para exemplificar, uma vez que o padrão do projeto é em inglês. Qualquer coisa me avisa.

2021-04-26 17:21 UTC, VitorLamego commented on hortum_mobile/lib/components/form_validation.dart
> +  }
Adicionar testes deste método.

2021-04-26 17:21 UTC, VitorLamego commented on hortum_mobile/lib/data/reclamation_register_backend.dart
> +  }
Seria interessante colocar os dois métodos na mesma classe. Não há necessidade de criar outra classe. Você já criou a classe "ReclamationDataApi" para lidar com a entidade de reclamação. Só fazer dois métodos dentro dessa classe, uma para puxar as reclamações cadastradas e o outro para cadastrar uma reclamação. Seguindo o padrão do projeto não faz sentido ter duas classes diferentes para lidar com uma mesma entidade.

Eu entendo que a parte de anúncios também está dessa forma, mas já pensando na refatoração dessa pasta, seria interessante já começarmos a mudar o que está chegando de novo, uma vez que essa pasta está ficando lotada de arquivos que tratam de entidades iguais.

2021-04-26 17:21 UTC, VitorLamego commented on hortum_mobile/lib/views/reclamation/components/list_reclamations.dart
> +class ReclamationsList extends StatefulWidget {
Essa classe poderia ser Stateless

2021-04-26 17:21 UTC, VitorLamego commented on hortum_mobile/lib/views/reclamation/components/reclamation_box.dart
> +    'Dart'.length;
Apagar a linha 24.

2021-04-26 17:21 UTC, VitorLamego commented on hortum_mobile/lib/views/reclamation/reclamation_page.dart
> +              ),
Isso aqui poderia ser um componente.

2021-04-26 17:21 UTC, VitorLamego commented on hortum_mobile/lib/views/reclamation/reclamation_page.dart
> +                    ),
Esse ícone no meu celular ficou desalinhado com o Container que o envolve. Para a tela do meu celular parece que ele ficou muito grande e então não está alinhado corretamente.

2021-04-26 17:21 UTC, VitorLamego commented on hortum_mobile/lib/views/reclamation/components/reclamation_box.dart
> +      sizeStringDescription = 0.60;
Esse if else para definir o tamanho da box não é visto como boa prática. O tamanho dessa box pode ser definida de maneira dinâmica de acordo com o próprio tamanho do texto. Para isso, basta não restringir a altura e adicionar um padding para que fique bom visualmente. 

Sendo assim, a caixa ("Box") vai variar o tamanho de acordo com o conteúdo que ela possui.

2021-04-26 17:21 UTC, VitorLamego commented on hortum_mobile/lib/views/reclamation/reclamation_page.dart
> +                                          fontSize: 11)),
Pode componentizar isso aqui também. Uma outra coisa em relação ao design da página. Acredito que se este botão estivesse na mesma linha do botão de Arrow Back o design ficaria melhor. Achei um pouco estranho a disposição em diagonal desses dois botões

2021-04-26 17:21 UTC, VitorLamego commented on hortum_mobile/lib/views/reclamation/services/reclamation_services.dart
> +      );
Por conta da padronização, seria interessante essa Dialog possuir algum arquivo dentro da pasta "components" desta tela. Aqui está misturando código do método de um serviço da página com código de interface visual.

2021-04-26 17:21 UTC, VitorLamego commented on hortum_mobile/lib/views/reclamation/components/reclamation_box.dart
> +                fontFamily: 'Roboto-Bold',
Acredito que o nome do Author poderia ter um destaque/estilização diferente da estilização da descrição.

2021-04-26 17:21 UTC, VitorLamego commented on hortum_mobile/test/reclamation_page_test.dart
> +    testWidgets('Show dialogue', (WidgetTester tester) async {
"Dialogue" está escrito errado.

2021-04-26 17:21 UTC, VitorLamego commented on hortum_mobile/test/reclamation_page_test.dart
> +      expect(find.byType(Scaffold), findsOneWidget);
Não é muito recomendável procurar pela presença de um Scaffold, tendo em vista que a maioria das páginas possuem o widget em sua árvore, portanto se por algum acaso o teste retorna para uma outra página que não a CustomerHomePage o teste continuaria passando.

2021-04-26 17:21 UTC, VitorLamego commented on hortum_mobile/lib/views/reclamation/components/reclamation_form.dart
> +}
Essa classe na verdade é uma page e não um component. Precisa trocar tanto o nome do arquivo como a pasta em que ele se encontra para seguir com os padrões do projeto. Sugiro também que separe os testes dessa interface em outro arquivo diferente da tela "ReclamationPage"

2021-04-26 17:21 UTC, VitorLamego commented on hortum_mobile/lib/views/reclamation/components/reclamation_form.dart
> +                                      top: 15, right: 165),
Esse padding de 165 fixo está quebrando a linha na tela do meu celular, ficando diferente de acordo com o que está no protótipo. Sugiro que não use valor tão alto e constante como foi utilizado, uma vez que dependendo do tamanho do dispositivo são ocasionados comportamentos diferentes.

2021-04-26 17:21 UTC, VitorLamego commented on hortum_mobile/lib/views/reclamation/components/reclamation_form.dart
> +                              ),
Essa árvore de widgets Container -> MaterialButton -> Container pra fazer o botão não é necessária. O child do MaterialButton é um Text apenas, ou o Align que foi utilizado, podendo ser estilizado com as propriedades do Text, do MaterialButton e do próprio Container de cima.

2021-04-27 21:45 UTC, brenno-silva requested changes
Quase tudo certo, e bom trabalho refatorando de _reclamation_ para _complaint_. Só é preciso algumas correções pequenas(Eu acho)

2021-04-27 21:45 UTC, brenno-silva commented on hortum_mobile/lib/views/complaint/components/complaint_box.dart
> +      sizeStringDescription = 0.60;
O que esse `sizeStringDescription` está fazendo?

2021-04-27 21:45 UTC, brenno-silva commented on hortum_mobile/test/register_complaint_page_test.dart
> +  // actualUser.email = 'user@gmail.com';
Remover comentário.

2021-04-27 21:45 UTC, brenno-silva commented on hortum_mobile/lib/views/complaint/components/list_complaints.dart
> +                style: TextStyle(color: Color(0xff1D8E40), fontSize: 15),
Quando não possui nenhuma reclamação o texto fica desalinhado.
![image](https://user-images.githubusercontent.com/54643530/116316425-4af6a100-a788-11eb-98dc-a51b4128136b.png)

2021-04-27 21:45 UTC, brenno-silva commented on hortum_mobile/test/complaint_page_test.dart
> +  // actualUser.email = 'user@gmail.com';
Remover comentário.

2021-04-27 22:05 UTC, CarlosFiuza commented on hortum_mobile/lib/views/complaint/components/complaint_box.dart
> +      sizeStringDescription = 0.60;
nada, esqueci de tirar, jurei que tinha tirado

2021-04-28 17:14 UTC, VitorLamego approved these changes
Agora sim !! Parabéns pelo trabalho e pela forma como foram feitas as mudanças !!

2021-04-28 17:27 UTC, brenno-silva approved these changes
Agora sim. Bom trabalho.

2021-04-28 17:30 UTC, merged