#89[US02] Apagar Conta
fga-eps-mds/2020.2-Hortum-Mobile pull request #44
Opened 2021-04-26 18:50 UTC by brenno-silva

## Descrição
- Adição da feature de excluir conta.

## Está consertando alguma issue aberta?
- [#89](https://github.com/fga-eps-mds/2020.2-Hortum/issues/89)

## Tarefas gerais realizadas
- Refatoração da UserProfile
- Adição da tela DeleteAccountPage e respectivos componentes e serviços
- Adição da AdvancedSettingsPage
- Refatoração de telas no protótipo
- Realização de testes unitários

## Testes 
- Caso o backend não tenha sido aprovado mude sua branch para a `feature/89-apagar-conta`
- Para testar entre no perfil, toque no botão "Avançado" e em seguida "Excluir conta"
- Insira sua senha(Caso queria testar o dialog de erro coloque a senha errada)
- Ao concluir o processo você será redirecionado a página de Login a conta terá sido excluída

2021-04-27 13:00 UTC, CarlosFiuza requested changes
Trabalho muito bom, funcionando muito bem. Só pedi algumas mudanças por questão de design e para padronizar o projeto

2021-04-27 13:00 UTC, CarlosFiuza commented on hortum_mobile/lib/data/user_delete_backend.dart
> +}
Como ja temos um data para change password, update user e delete user, seria melhor que todos esses datas ficassem em uma classe só, por exemplo `user_data_backend`. Ai cada um desses datas citados seriam um método dessa classe

2021-04-27 13:00 UTC, CarlosFiuza commented on hortum_mobile/lib/views/advanced_settings/components/change_password_button.dart
> +              (route) => route.isCurrent);
Usar esse `Navigator.pushAndremoveUntil()` faz com que caso o usuário aperte o botão voltar ele saia da aplicação, seria melhor usar só o `Navigator.push()` pra que ele volte pra tela advanced_settings

2021-04-27 13:00 UTC, CarlosFiuza commented on hortum_mobile/lib/views/advanced_settings/components/delete_account_button.dart
> +              (route) => route.isCurrent);
Usar esse `Navigator.pushAndremoveUntil()` faz com que caso o usuário aperte o botão voltar ele saia da aplicação, seria melhor usar só o `Navigator.push()` pra que ele volte pra tela advanced_settings

2021-04-27 13:00 UTC, CarlosFiuza commented on hortum_mobile/lib/views/advanced_settings/components/logout_button.dart
> +              (route) => route.isCurrent);
Usar esse `Navigator.pushAndremoveUntil()` faz com que caso o usuário aperte o botão voltar ele saia da aplicação, seria melhor usar só o `Navigator.push()` pra que ele volte pra tela advanced_settings

2021-04-27 13:00 UTC, CarlosFiuza commented on hortum_mobile/lib/views/advanced_settings/advanced_settings_page.dart
> +                      LogoutButton(),
Acho que o design desses botões ficou feio kkkk, colocar o material button dentro de um container com box decoration ficaria com um visual bem melhor

2021-04-27 13:00 UTC, CarlosFiuza commented on hortum_mobile/lib/views/delete_account/services/delete_account_services.dart
> +    );
Poderia colocar esse dialog em um componente, pois no service altera sua funcão

2021-04-27 14:38 UTC, brenno-silva commented on hortum_mobile/lib/data/user_delete_backend.dart
> +}
Realmente faz sentido.

2021-04-27 14:44 UTC, brenno-silva commented on hortum_mobile/lib/views/advanced_settings/advanced_settings_page.dart
> +                      LogoutButton(),
Aí vou ter que discordar kkkk. Acaba fugindo do padrão dos botões do projeto, os que utilizam a box decoration normalmente são os que fazem alguma requisição ao banco(Cadastro, login, criar anúncio, alterar dados do usuário)

2021-04-27 14:59 UTC, brenno-silva commented on hortum_mobile/lib/views/advanced_settings/components/logout_button.dart
> +              (route) => route.isCurrent);
Nesse caso faz mais sentido usar o `pushAndremoveUntil()`, já que ao pressionar o botão o usuário estará saindo da conta. Se permitisse ele retornar, o usuário estaria utilizando a aplicação com o `actualUser = null`

2021-04-27 20:08 UTC, CarlosFiuza commented on hortum_mobile/lib/views/advanced_settings/components/logout_button.dart
> +              (route) => route.isCurrent);
Sim, viajei na hora que comentei kkk

2021-04-27 20:23 UTC, CarlosFiuza approved these changes
Show, funcionando certinho, parabéns pelo trabalho e principalmente pelos testes!

2021-04-29 02:32 UTC, vital14 approved these changes
Bom Trabalho nos concertos que o Carlos pontuou, funcionou bem

2021-04-29 03:13 UTC, merged