#205 Refatorações na página de criar anúncio
fga-eps-mds/2020.2-Hortum-Mobile pull request #45
Opened 2021-05-01 20:51 UTC by brenno-silva

## Descrição
- Alteração de campo de descrição e adição de dialog.

## Está consertando alguma issue aberta?
- [#205](https://github.com/fga-eps-mds/2020.2-Hortum/issues/205)

## Tarefas gerais realizadas
- Refatoração de testes
- Adição de dialog
- Refatoração do campo de descrição

2021-05-02 03:39 UTC, Joao-Moura requested changes
Funcionando perfeitamente, parabens. A única coisa que eu percebi e que me incomodou um pouco são os espaços entre os campos da tela de registro de anúncio (parece que ficou menor) kkkkkkkk. E outra (essa daqui não precisa fazer), em vez de utilizar uma mensagem estática no dialog usar a que vem do backend.

2021-05-03 17:31 UTC, VitorLamego requested changes
Parabéns pelo trabalho !! Encontrei só essas questões relacionadas aos padrões do projeto e também relacionados à fidelidade da identidade visual e usabilidade do aplicativo.

2021-05-03 17:31 UTC, VitorLamego commented on hortum_mobile/lib/views/register_announcement/components/announ_register_form.dart
> +              ),
O campo de descrição está com uma largura de borda diferente dos outros campos. Adicionaria um width de 1.5 para ficar mais similar aos outros campos do formulários

2021-05-03 17:31 UTC, VitorLamego commented on hortum_mobile/lib/views/register_announcement/announcement_register_page.dart
> +      resizeToAvoidBottomInset: false,
Com o resizeToAvoidBottomInset quando o usuário vai escrever a descrição do anúncio o teclado do celular sobrepões o campo. Anteriormente isso tinha sido corrigido nas páginas com formulário.

2021-05-03 17:31 UTC, VitorLamego commented on hortum_mobile/lib/views/register_announcement/components/announ_register_form.dart
> +            ),
Existem vários Paddings como esse neste arquivo e não se tem nenhum conteúdo para utilização desse widget. Para desempenhar o mesmo comportamento que o Padding está fazendo normalmente é utilizado uma SizedBox para dar tal espaçamento e não o widget Padding sem nenhum child

2021-05-03 17:31 UTC, VitorLamego commented on hortum_mobile/lib/views/register_announcement/services/error_message_format.dart
> +class Formarter {
Não vejo necessidade em ter uma classe Formater uma vez que já tem o arquivo de serviços do RegisteraAnnouncements e isso poderia ser simplesmente um método no outro arquivo.

2021-05-04 14:53 UTC, Joao-Moura approved these changes
Funcionando perfeitamente, parabéns

2021-05-04 15:55 UTC, VitorLamego approved these changes
Ótimo trabalho !!

2021-05-04 18:25 UTC, merged