#204 Correção Tela Detalhes do Produtor
fga-eps-mds/2020.2-Hortum-Mobile pull request #47
Opened 2021-05-03 16:27 UTC by VitorLamego

## Descrição
Nesta issue foi corrigido o overflow do nome e também o erro quando o produtor não possuía nenhum anúncio cadastrado

## Está concertando alguma issue aberta?
#204

## Tarefas gerais realizadas
- Fixado a largura do nome na Row para evitar Overflow
- Adição de parâmetro name obrigatório na página ProductorDetailsPage
- Criação de widget (Text) para quando o produtor não tiver nenhum anúncio cadastrado
- Adição de testes referentes ao serviço adicionado

## Teste
Para testar as alterações siga os passos:
1. Crie um produtor novo. Coloque nome e sobrenome.
2. Crie um consumidor
3. Acesse a página de detalhes por meio da visualização dos produtor cadastrados na HomeCustomerPage
4. Verifique se a página não está quebrando e a presença do aviso dizendo que o produtor não possui anúncios ainda.
5. Verifique o comportamento do nome do produtor na página.

2021-05-03 18:35 UTC, Joao-Moura requested changes
O overflow da página de detalhes do produtor foi corrigida corretamente, parabéns. Só vou deixar dois comentários aqui que eu acho que dariam para melhorar.
1. Não sei se é possível, mais se der tentar aumentar um pouco o tamanho das linhas do nome quando ele é muito grande, para caber mais caracteres (não é obrigatório)
2. O segundo é que da pra tirar o icone de compartilhar produtor, já que a gente não tem mais a issue de compartilhar

2021-05-03 18:35 UTC, Joao-Moura commented on hortum_mobile/lib/views/productor_details/services/productor_details_services.dart
> +        "Este produtor não possui anúncios disponíveis no momento !!",
A mensagem ficou com dois !

2021-05-03 18:38 UTC, Joao-Moura commented
E se você quiser corrigir outro overflow que eu encontrei na homepage do customer quando o nome do produtor é muito grande (se não quiser eu abro uma issue de bug kkkkkk).
![image](https://user-images.githubusercontent.com/46077033/116917777-a15b5800-ac3e-11eb-807e-7ae82a69d7d5.png)

2021-05-03 18:59 UTC, VitorLamego commented
Beleza, vou usar o espaço desse ícone de compartilhar para aumentar a linha, mas talvez tenha que diminuir o tamanho da fonte um pouco pra ficar melhor, mas eu faço essa alteração.

Quanto ao overflow da ProductorBox eu posso dar uma olhada já. Mais tarde solicito revisão sua de novo.

2021-05-03 19:01 UTC, Joao-Moura commented
@VitorLamego tava falando com o brenno aqui e ele ja corrigiu esse erro do overflow na branch de favoritos kkkkkk

2021-05-04 01:03 UTC, brenno-silva requested changes
O container do nome acaba ocupando muito espaço quando o nome é grande, no mais, o código ficou bem organizado.

2021-05-04 01:03 UTC, brenno-silva commented on hortum_mobile/lib/views/productor_details/components/name_actions.dart
> +              textAlign: TextAlign.center,
Acredito que seja melhor a deixar a página inteira num scroll ou colocar um Flexible/Expanded para limitar o espaço utilizado pelo nome, pois quando o nome do usuário é muito grande ocorre overflow na parte de baixo da tela.

![image](https://user-images.githubusercontent.com/54643530/116950038-40417d80-ac5a-11eb-90ac-a07ed70a5754.png)

2021-05-04 13:12 UTC, VitorLamego commented on hortum_mobile/lib/views/productor_details/components/name_actions.dart
> +              textAlign: TextAlign.center,
Bom eu fiquei na dúvida quanto à revisão. O @Joao-Moura solicitou que aumentasse mais o Container para caber mais caracteres, e o @brenno-silva pediu que diminuísse kkk.

Eu posso arrumar isso, mas não tendo uma limitação do tamanho do nome de usuário no form de cadastro acaba apenas passando o overflow para outro lugar.
1. Se eu diminuo o tamanho do container que possui o nome , limitando a sua altura, consequentemente ele passaria esse overflow para o Container.
2. Se eu deixar da maneira que está ele ocupará muito espaço, podendo ocasionar overflow em casos de testes que o nome é absurdamente grande.

Quanto ao novo overflow que foi enviado na imagem, qual foi o nome do produtor que você utilizou ?? Coloquei alguns nomes grandes aqui, mas não consegui reproduzir o erro.

2021-05-04 13:40 UTC, Joao-Moura commented on hortum_mobile/lib/views/productor_details/components/name_actions.dart
> +              textAlign: TextAlign.center,
Pois é, eu também não tive overflow na parte inferior com um nome gigante. Acho que a gente acabou falando a mesma coisa só que de forma diferente, a ideia seria algo assim:
```
 cascascas
ascascapismc
   ascasc
```
para:
```
cascascasascasc
 apismcascasc
```

2021-05-04 13:51 UTC, VitorLamego commented on hortum_mobile/lib/views/productor_details/components/name_actions.dart
> +              textAlign: TextAlign.center,
Eu fiz algumas alterações aqui tentando melhorar essas duas questões. Vou solicitar a revisão novamente, se os erros persistirem me avisem que ai eu acho que a gente teria que diminuir um pouco a fonte.

2021-05-04 13:52 UTC, brenno-silva commented on hortum_mobile/lib/views/productor_details/components/name_actions.dart
> +              textAlign: TextAlign.center,
> Bom eu fiquei na dúvida quanto à revisão. O @Joao-Moura solicitou que aumentasse mais o Container para caber mais caracteres, e o @brenno-silva pediu que diminuísse kkk.
> 
> Eu posso arrumar isso, mas não tendo uma limitação do tamanho do nome de usuário no form de cadastro acaba apenas passando o overflow para outro lugar.
> 
>     1. Se eu diminuo o tamanho do container que possui o nome , limitando a sua altura, consequentemente ele passaria esse overflow para o Container.
> 
>     2. Se eu deixar da maneira que está ele ocupará muito espaço, podendo ocasionar overflow em casos de testes que o nome é absurdamente grande.
> 
> 
> Quanto ao novo overflow que foi enviado na imagem, qual foi o nome do produtor que você utilizou ?? Coloquei alguns nomes grandes aqui, mas não consegui reproduzir o erro.

@VitorLamego Nos testes que fiz usei nomes com mais de 90 caracteres(Existe um limite no backend de 100 caracteres). Pode até deixar o tamanho adaptativo como está porém incluí-lo no scroll.
@Joao-Moura o overflow que falei é diferente.

2021-05-04 14:59 UTC, Joao-Moura approved these changes
Tudo ok por aqui, só uma coisa que eu notei aqui é que a caixa de scroll não ta colada no footer, mais isso é coisa extra, parabéns pelo trabalho.

2021-05-04 15:15 UTC, brenno-silva reviewed
Ficou melhor, porém só diminuiu o overflow de 121 para 4.7 pixels. Diminuindo a fonte para 24 corrige o overflow, porém o texto fica escondido no footer.
![image](https://user-images.githubusercontent.com/54643530/117026225-fbf1c400-acd1-11eb-91ae-3c31ca99dabf.png)

2021-05-04 15:32 UTC, VitorLamego commented
Qual o nome do produtor que você está testando @brenno-silva ?

2021-05-04 16:06 UTC, brenno-silva commented
> Qual o nome do produtor que você está testando @brenno-silva ? E o dispositivo que você está usando ?

Nome: "Nomevmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhhhhhhhhhhhhhhhhhhhhhhhhhhmmmmmmmmmmmmmmmmmmmmmmmmm"
Dispositivo: Zenfone Max Plus m2

2021-05-04 16:19 UTC, VitorLamego commented
Po kkkk mas ai esse nome vai quebrar mesmo. Eu adicionei agora um método para lidar com nomes com bastante sobrenome, mas pra esse tipo de nome ai realmente não tem nenhum tratamento, até porque é um nome completamente irreal kkkkk

2021-05-04 17:03 UTC, brenno-silva commented
> Po kkkk mas ai esse nome vai quebrar mesmo. Eu adicionei agora um método para lidar com nomes com bastante sobrenome, mas pra esse tipo de nome ai realmente não tem nenhum tratamento, até porque é um nome completamente irreal kkkkk

Mesmo sendo irreal não temos nenhum impedimento para o usuário criar um nome desse. O PR será aprovado, mas futuramente teremos que cuidar dessa validação.

2021-05-04 17:03 UTC, brenno-silva approved these changes

2021-05-04 17:05 UTC, VitorLamego commented
Sim compreendo. Mas ai a aceitação desse tipo de nome já não entra no escopo dessa issue, mas realmente precisamos abrir um hotfix para tratar entradas desse tipo. Obrigado.

2021-05-04 17:05 UTC, merged