#182 Implementação Localização
fga-eps-mds/2020.2-Hortum-Mobile pull request #48
Opened 2021-05-05 13:51 UTC by CarlosFiuza

## Descrição
- Mudança na tela de registro de anúncio para permitir cadastrar até 3 localizações
- Mudança na tela de edição de anúncio para editar localizações

## Está concertando alguma issue aberta?
- [#182](https://github.com/fga-eps-mds/2020.2-Hortum/issues/182)

## Tarefas gerais realizadas
- Modificação na page registro de anúncio
- Modificação na tela de edição de anúncio
- Modificação no announcements data de registro e edição de anúncios
- Modificações nos testes de acordo com o que foi implementado

2021-05-05 21:46 UTC, brenno-silva requested changes
Apenas uma pequena mudança. Muito bom!

2021-05-05 21:46 UTC, brenno-silva commented on hortum_mobile/lib/views/register_announcement/components/announ_register_form.dart
>                padding: EdgeInsets.only(bottom: paddingSize),
Trocando esse padding no `bottom` por um no `top` evita que fique um espaço entre a caixa com as localizações e o formfield

2021-05-06 02:10 UTC, CarlosFiuza commented on hortum_mobile/lib/views/register_announcement/components/announ_register_form.dart
>                padding: EdgeInsets.only(bottom: paddingSize),
Fazendo isso ficaria traria o field de localização mais pra baixo. Adicionei um padding top no field de categoria e alinhou certinho

2021-05-06 03:29 UTC, brenno-silva approved these changes
Excelente!

2021-05-06 13:47 UTC, matheuscvp approved these changes
Ótimo! Implementação feita com sucesso

2021-05-06 13:53 UTC, merged