#99/100[US13/14] - Visualizar e Pesquisar Localizacoes
fga-eps-mds/2020.2-Hortum-Mobile pull request #53
Opened 2021-05-07 21:39 UTC by brenno-silva

## Descrição
- Adaptação da interface para para pesquisa e visualização de localizações

## Está consertando alguma issue aberta?
- [#99](https://github.com/fga-eps-mds/2020.2-Hortum/issues/99) e [#100](https://github.com/fga-eps-mds/2020.2-Hortum/issues/99)

## Tarefas gerais realizadas
- Alterado botões do filtro
- Alterada url de pesquisa
- Passagem das localizações vindas do backend
- Refatorado box das localizações
- Corrigido testes

2021-05-08 15:49 UTC, CarlosFiuza requested changes
Muito bom trabalho, funcionando perfeitamente

2021-05-08 15:49 UTC, CarlosFiuza commented on hortum_mobile/lib/views/home_customer/services/home_customer_services.dart
> +      await announData.getAnnoun(filter, type);
aqui poderia colocar apenas 1 if, 
`if (type == "name" || type == "localizations__adress") {
      await announData.getAnnoun(filter, type);
    } else {
      await productorsData.getProductors(filter);
    }`

2021-05-10 15:24 UTC, CarlosFiuza approved these changes

2021-05-10 15:29 UTC, matheuscvp approved these changes
Boa implementação parabéns!

2021-05-10 20:34 UTC, merged