#219 Deixar anúncio invisível
fga-eps-mds/2020.2-Hortum-Mobile pull request #57
Opened 2021-05-11 21:02 UTC by LucasBraunX

## Descrição
- Funcionalidade de alterar a visibilidade de um anúncio.

## Está consertando alguma issue aberta?
- [#219](https://github.com/fga-eps-mds/2020.2-Hortum/issues/219)

## Tarefas gerais realizadas
- Adicionada funcionalidade do botão de visibilidade de anúncios
- Adicionado testes do botão de visiblidade de anúncios

2021-05-11 22:12 UTC, brenno-silva requested changes
Bom trabalho, talvez precise adicionar uma linha de código apenas para melhorar a usabilidade.

2021-05-11 22:12 UTC, brenno-silva commented on hortum_mobile/lib/views/home_productor/components/buttons_row.dart
> +                Navigator.push(context, MaterialPageRoute(builder: (context) {
Acredito que adicionando um `Navigator.pop(context);` antes do `Navigator.push` melhoraria a navegação por fazer com que não fique "empilhando" as páginas as pressionar o botão.

2021-05-11 22:13 UTC, CarlosFiuza commented on hortum_mobile/lib/views/home_productor/components/buttons_row.dart
> +                Navigator.push(context, MaterialPageRoute(builder: (context) {
ao adicionar o Navigator.pop ele volta pra página de login

2021-05-11 22:29 UTC, brenno-silva commented on hortum_mobile/lib/views/home_productor/components/buttons_row.dart
> +                Navigator.push(context, MaterialPageRoute(builder: (context) {
Ah sim, nos meus testes tinha feito depois de já ter navegado por outras páginas.

2021-05-11 22:29 UTC, brenno-silva approved these changes

2021-05-12 21:13 UTC, vital14 approved these changes
Depois de muito tempo tentando entender o problema na tela vermelha, ele foi resolvido no back e então funcionou perfeitamente, parabéns

2021-05-12 21:16 UTC, merged