#117 Tela Meu Perfil
fga-eps-mds/2020.2-Hortum-Mobile pull request #8
Opened 2021-03-24 20:31 UTC by VitorLamego

## Descrição
Foi criado a interface da tela "Meu Perfil", de acordo com o protótipo

## Está concertando alguma issue aberta?
#117

## Tarefas gerais realizadas
- Criação da tela Meu Perfil

2021-03-24 23:31 UTC, Joao-Moura requested changes
Em relação a página eu não encontrei nenhum problema, só fiquei confuso em relação à que página do protótipo ela faz parte (acredito ser algo relacionado as configurações do perfil ?). No mais é isso, gostei do estilo da página

2021-03-24 23:31 UTC, Joao-Moura commented on hortum_mobile/lib/view/profile/profile.dart
> +                      child: ListView(
Utilizar o ListView aqui seria a melhor opção ? Porque na parte do formúlaro eu consigo ficar mexendo com ele para cima e para baixo. Segue foto do comportamento:
![image](https://user-images.githubusercontent.com/46077033/112396863-e794d180-8cf8-11eb-8cfd-56038ed2bf87.png)

2021-03-25 00:56 UTC, brenno-silva commented on hortum_mobile/lib/view/profile/profile.dart
> +                      child: ListView(
Sobre a parte do protótipo, essa tela é acionada quando o usuário entra em perfil.

2021-03-25 13:55 UTC, VitorLamego commented
@Joao-Moura essa é a tela "Meu Perfil" referente ao protótipo. O design dela sofreu algumas alterações durante a issue de refatoração do protótipo, talvez por isso não tenha reconhecido.

2021-03-25 17:10 UTC, LucasBraunX requested changes

2021-03-25 17:10 UTC, LucasBraunX commented on hortum_mobile/lib/data/login_backend.dart
> +    var url = 'http://192.168.15.11:8000/login/';
Deixou seu ip ai

2021-03-25 17:15 UTC, VitorLamego commented on hortum_mobile/lib/data/login_backend.dart
> +    var url = 'http://192.168.15.11:8000/login/';
Resolvido.

2021-03-25 17:19 UTC, Joao-Moura requested changes
@VitorLamego, vi aqui o novo protótipo e tudo ok essa parte. Só deixando uns comentários aqui sobre a conexão com o back.

2021-03-25 17:19 UTC, Joao-Moura commented on hortum_mobile/lib/data/login_backend.dart
> +    var url = 'http://192.168.15.11:8000/login/';
Só lembrando de retirar o ip pra IPLOCAL

2021-03-25 17:19 UTC, Joao-Moura commented on hortum_mobile/lib/data/login_backend.dart
> +    mapResponse['password'] = password;
Essa linha é realmente necessária, já que ela é mapeada no model User. Não seria só acessar o globals ?

2021-03-25 17:19 UTC, Joao-Moura commented on hortum_mobile/lib/data/login_backend.dart
> +    var url = 'http://192.168.15.11:8000/login/';
Eita foi sem querer esse daqui.

2021-03-25 17:24 UTC, VitorLamego commented on hortum_mobile/lib/data/login_backend.dart
> +    mapResponse['password'] = password;
A linha é necessária porque a requisição no back não retorna o "password" do usuário, até porque ele retornaria a senha com o hash, que é o que está armazenado no banco. Sendo assim, a única maneira de armazenar a senha "pura" do usuário, para a correta apresentação na tela "Meu Perfil" é armazenando a senha quando ele inserir no login, portanto a utilidade dessa linha é acrescentar ao objeto json que será passado à model User, a chave-valor do "password"

2021-03-25 17:28 UTC, Joao-Moura commented on hortum_mobile/lib/data/login_backend.dart
> +    mapResponse['password'] = password;
Entendi, faz sentido. Porém eu acredito que seja ruim armazenar a senha em formato plain text no front, não seria melhor transferir essas tarefas que necessitem da senha pro backend ?

2021-03-25 17:37 UTC, VitorLamego commented on hortum_mobile/lib/data/login_backend.dart
> +    mapResponse['password'] = password;
O form de atualizar o perfil do aluno apresenta os valores atuais do usuário (Nome, email e senha), sendo a senha em um campo com ObscureText. Para apresentação dessa senha no campo, em algum momento seria necessário armazenar ela em alguma variável, mesmo vindo na reposta de uma requisição. Além disso, não sei se o banco consegue retornar a senha sem o hash. Se não quiser armazenar essa senha, seria necessário uma refatoração nessa tela, retirando esse campo de senha e colocando em outro local essa atualização de senha.

2021-03-25 17:40 UTC, Joao-Moura commented on hortum_mobile/lib/data/login_backend.dart
> +    mapResponse['password'] = password;
Entendi, acredito que seja legal a gente dar uma estudada melhor nisso no futuro, mais para o estado atual do programa está perfeito.

2021-03-25 17:41 UTC, Joao-Moura approved these changes
Valeu pelo PR

2021-03-25 18:51 UTC, LucasBraunX approved these changes

2021-03-25 19:17 UTC, merged